apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: user-management
  labels:
    app: postgresql
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cGFzc3dvcmQ=
  database: dXNlcl9tYW5hZ2VtZW50