apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: user-management
  labels:
    app: user-management-app
data:
  APP_NAME: "user-management-system"
  APP_VERSION: "1.0.0"
  SPRING_PROFILES_ACTIVE: "prod"